/* Luckee Listing analytics constants. Shared by the SDK and Listing adapter. */
(function () {
  const APP_ID = "luckee-listing";
  const SOURCE_APP = "listing-optimizer";
  const TOOL_ID = "listing-optimizer";

  const CANONICAL_EVENTS = Object.freeze({
    LANDING_VIEW: "listing_landing_view",
    PAGE_VIEW: "listing_page_view",
    CTA_CLICK: "listing_cta_click",
    ASIN_ENTERED: "listing_asin_entered",
    ASIN_SUBMIT: "listing_asin_submit",
    AUTH_GATE_VIEW: "listing_auth_gate_view",
    SIGNUP_INTENT: "listing_signup_intent",
    LOGIN_SUBMIT: "listing_login_submit",
    LOGIN_RESULT: "listing_login_result",
    AUTH_COMPLETE: "listing_auth_complete",
    AUDIT_MODE_CHANGE: "listing_audit_mode_change",
    ATTACHMENT_UPLOAD_RESULT: "listing_attachment_upload_result",
    AUDIT_STARTED: "listing_audit_started",
    AUDIT_BLOCKED: "listing_audit_blocked",
    AUDIT_PHASE_VIEW: "listing_audit_phase_view",
    AUDIT_FAILED: "listing_audit_failed",
    REPORT_READY: "listing_report_ready",
    REPORT_VIEW: "listing_report_view",
    REPORT_ENGAGE: "listing_report_engage",
    OPTIMIZE_CLICK: "listing_optimize_click",
    FREE_BUNDLE_GATE_VIEW: "listing_free_bundle_gate_view",
    FREE_BUNDLE_CONFIRM: "listing_free_bundle_confirm",
    CREDIT_GATE_VIEW: "listing_credit_gate_view",
    CREDIT_GATE_DECISION: "listing_credit_gate_decision",
    CREDIT_CONFIRM: "listing_credit_confirm",
    WORKSPACE_OPEN: "listing_workspace_open",
    WORKSPACE_TAB_CLICK: "listing_workspace_tab_click",
    FIX_VALIDATION_BLOCK: "listing_fix_validation_block",
    FIX_ACCEPT: "listing_fix_accept",
    FIX_EDIT: "listing_fix_edit",
    FIX_REJECT: "listing_fix_reject",
    FIX_AUTO_COPY: "listing_fix_auto_copy",
    FIX_MANUAL_COPY: "listing_fix_manual_copy",
    SUGGESTION_DECISION: "listing_suggestion_decision",
    REAUDIT_CLICK: "listing_reaudit_click",
    EXPORT_CLICK: "listing_export_click",
    EXPORT_COPY: "listing_export_copy",
    EXPORT_DOWNLOAD: "listing_export_download",
    COMPLETED_LOOP: "listing_completed_loop",
    SUBSCRIPTION_GATE_VIEW: "listing_subscription_gate_view",
    SUBSCRIBE_CLICK: "listing_subscribe_click",
    CHECKOUT_STARTED: "listing_checkout_started",
    CHECKOUT_CANCELLED: "listing_checkout_cancelled",
    SUBSCRIPTION_SUCCESS: "listing_subscription_success"
  });

  const LEGACY_EVENTS = Object.freeze({
    PAGE_VIEW: "LISTING_PAGE_VIEW",
    CTA_CLICK: "LISTING_CTA_CLICK",
    PLAN_CTA_CLICK: "LISTING_PLAN_CTA_CLICK",
    ASIN_ENTERED: "LISTING_ASIN_ENTERED",
    AUTH_MODAL_OPEN: "LISTING_AUTH_MODAL_OPEN",
    SIGNUP_INTENT: "LISTING_SIGNUP_INTENT",
    LOGIN_SUBMIT: "LISTING_LOGIN_SUBMIT",
    LOGIN_RESULT: "LISTING_LOGIN_RESULT",
    AUDIT_MODE_CHANGE: "LISTING_AUDIT_MODE_CHANGE",
    AUDIT_START_CLICK: "LISTING_AUDIT_START_CLICK",
    ATTACHMENT_UPLOAD_RESULT: "LISTING_ATTACHMENT_UPLOAD_RESULT",
    AUDIT_RUN_START: "LISTING_AUDIT_RUN_START",
    AUDIT_BLOCKED: "LISTING_AUDIT_BLOCKED",
    AUDIT_RUN_RESULT: "LISTING_AUDIT_RUN_RESULT",
    REPORT_READY: "LISTING_REPORT_READY",
    REPORT_VIEW: "LISTING_REPORT_VIEW",
    REPORT_ENGAGE: "LISTING_REPORT_ENGAGE",
    OPTIMIZATION_CTA_CLICK: "LISTING_OPTIMIZATION_CTA_CLICK",
    FREE_BUNDLE_GATE_VIEW: "LISTING_FREE_BUNDLE_GATE_VIEW",
    FREE_BUNDLE_CONFIRM: "LISTING_FREE_BUNDLE_CONFIRM",
    SUBSCRIPTION_GATE_VIEW: "LISTING_SUBSCRIPTION_GATE_VIEW",
    CREDIT_MODAL_VIEW: "LISTING_CREDIT_MODAL_VIEW",
    CREDIT_MODAL_DECISION: "LISTING_CREDIT_MODAL_DECISION",
    WORKSPACE_VIEW: "LISTING_WORKSPACE_VIEW",
    WORKSPACE_TAB_CLICK: "LISTING_WORKSPACE_TAB_CLICK",
    SUGGESTION_DECISION: "LISTING_SUGGESTION_DECISION",
    REAUDIT_CLICK: "LISTING_REAUDIT_CLICK",
    EXPORT_OPEN: "LISTING_EXPORT_OPEN",
    EXPORT_COPY: "LISTING_EXPORT_COPY",
    APLUS_BRIEF_DOWNLOAD: "LISTING_APLUS_BRIEF_DOWNLOAD",
    FIX_AUTO_COPY: "LISTING_FIX_AUTO_COPY",
    FIX_MANUAL_COPY: "LISTING_FIX_MANUAL_COPY",
    FIX_VALIDATION_BLOCK: "LISTING_FIX_VALIDATION_BLOCK",
    CHECKOUT_STARTED: "LISTING_CHECKOUT_STARTED",
    CHECKOUT_CANCELLED: "LISTING_CHECKOUT_CANCELLED",
    SUBSCRIPTION_SUCCESS: "LISTING_SUBSCRIPTION_SUCCESS",
    COMPLETED_LOOP: "LISTING_COMPLETED_LOOP"
  });

  const EVENT_ALIASES = Object.freeze({
    LISTING_CTA_CLICK: CANONICAL_EVENTS.CTA_CLICK,
    LISTING_ASIN_ENTERED: CANONICAL_EVENTS.ASIN_ENTERED,
    LISTING_AUTH_MODAL_OPEN: CANONICAL_EVENTS.AUTH_GATE_VIEW,
    LISTING_SIGNUP_INTENT: CANONICAL_EVENTS.SIGNUP_INTENT,
    LISTING_LOGIN_SUBMIT: CANONICAL_EVENTS.LOGIN_SUBMIT,
    LISTING_LOGIN_RESULT: CANONICAL_EVENTS.LOGIN_RESULT,
    LISTING_AUDIT_MODE_CHANGE: CANONICAL_EVENTS.AUDIT_MODE_CHANGE,
    LISTING_AUDIT_START_CLICK: CANONICAL_EVENTS.ASIN_SUBMIT,
    LISTING_ATTACHMENT_UPLOAD_RESULT: CANONICAL_EVENTS.ATTACHMENT_UPLOAD_RESULT,
    LISTING_AUDIT_RUN_START: CANONICAL_EVENTS.AUDIT_STARTED,
    LISTING_AUDIT_BLOCKED: CANONICAL_EVENTS.AUDIT_BLOCKED,
    LISTING_REPORT_READY: CANONICAL_EVENTS.REPORT_READY,
    LISTING_REPORT_VIEW: CANONICAL_EVENTS.REPORT_VIEW,
    LISTING_REPORT_ENGAGE: CANONICAL_EVENTS.REPORT_ENGAGE,
    LISTING_OPTIMIZATION_CTA_CLICK: CANONICAL_EVENTS.OPTIMIZE_CLICK,
    LISTING_FREE_BUNDLE_GATE_VIEW: CANONICAL_EVENTS.FREE_BUNDLE_GATE_VIEW,
    LISTING_FREE_BUNDLE_CONFIRM: CANONICAL_EVENTS.FREE_BUNDLE_CONFIRM,
    LISTING_SUBSCRIPTION_GATE_VIEW: CANONICAL_EVENTS.SUBSCRIPTION_GATE_VIEW,
    LISTING_CREDIT_MODAL_VIEW: CANONICAL_EVENTS.CREDIT_GATE_VIEW,
    LISTING_WORKSPACE_VIEW: CANONICAL_EVENTS.WORKSPACE_OPEN,
    LISTING_WORKSPACE_TAB_CLICK: CANONICAL_EVENTS.WORKSPACE_TAB_CLICK,
    LISTING_REAUDIT_CLICK: CANONICAL_EVENTS.REAUDIT_CLICK,
    LISTING_EXPORT_OPEN: CANONICAL_EVENTS.EXPORT_CLICK,
    LISTING_EXPORT_COPY: CANONICAL_EVENTS.EXPORT_COPY,
    LISTING_APLUS_BRIEF_DOWNLOAD: CANONICAL_EVENTS.EXPORT_DOWNLOAD,
    LISTING_FIX_AUTO_COPY: CANONICAL_EVENTS.FIX_AUTO_COPY,
    LISTING_FIX_MANUAL_COPY: CANONICAL_EVENTS.FIX_MANUAL_COPY,
    LISTING_FIX_VALIDATION_BLOCK: CANONICAL_EVENTS.FIX_VALIDATION_BLOCK,
    LISTING_CHECKOUT_STARTED: CANONICAL_EVENTS.CHECKOUT_STARTED,
    LISTING_CHECKOUT_CANCELLED: CANONICAL_EVENTS.CHECKOUT_CANCELLED,
    LISTING_SUBSCRIPTION_SUCCESS: CANONICAL_EVENTS.SUBSCRIPTION_SUCCESS,
    LISTING_COMPLETED_LOOP: CANONICAL_EVENTS.COMPLETED_LOOP
  });

  const ATTRIBUTION_KEYS = Object.freeze([
    "gclid",
    "gbraid",
    "wbraid",
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_content",
    "utm_term",
    "google_campaign_id",
    "google_ad_group_id",
    "google_keyword",
    "google_target_id",
    "google_match_type",
    "google_network",
    "google_device",
    "google_creative_id",
    "google_keyword_id",
    "landing_variant"
  ]);

  const TOP_LEVEL_KEYS = Object.freeze([
    "asin",
    "marketplace",
    "audit_id",
    "auditId",
    "report_id",
    "reportId",
    "bundle_id",
    "bundleId",
    "thread_id",
    "threadId",
    "workspace_id",
    "workspaceId",
    "subscription_id",
    "subscriptionId",
    "checkout_session_id",
    "checkoutSessionId",
    "order_id",
    "orderId",
    "conversion_value",
    "conversionValue",
    "currency",
    "plan_id",
    "planId",
    "plan_price",
    "planPrice",
    "purchase_type",
    "purchaseType",
    "checkout_type",
    "checkoutType",
    "product_type",
    "productType",
    "billing_type",
    "billingType",
    "pack_id",
    "packId",
    "stripe_price_id",
    "stripePriceId",
    "completion_source",
    "completionSource",
    "clipboard_result",
    "clipboardResult",
    "is_sample",
    "isSample",
    "dataMode"
  ]);

  window.LuckeeAnalyticsConfig = Object.freeze({
    APP_ID,
    SOURCE_APP,
    TOOL_ID,
    ENDPOINT: "luckee/user/web/analytics/events/batch.do",
    STORAGE_PREFIX: "luckee-listing:analytics",
    REGISTER_CHANNEL_KEY: "register_channel",
    DEFAULT_AUTH_EVENT_NAME: CANONICAL_EVENTS.AUTH_COMPLETE,
    USER_STORAGE_KEYS: Object.freeze(["luckee-listing:user", "user"]),
    CANONICAL_EVENTS,
    LEGACY_EVENTS,
    EVENT_ALIASES,
    ATTRIBUTION_KEYS,
    TOP_LEVEL_KEYS
  });
})();
